"""Deploy per-context instruction components into a context's Drive folder.

Triggered by Extension on workspace open (`POST /deploy-instructions`). Reads a
context's `context.json` declarations and materializes them next to the context:

- ``skills`` → ``<context>/.claude/skills/<name>/`` (Duet-managed: deploy the
  declared set, prune everything else). Absent key → no-op; present (even ``[]``)
  → manage.
- ``instructions`` → ``CLAUDE.md`` / ``AGENTS.md`` / ``GEMINI.md`` at the context
  root, composed from per-client templates in this package. Always generated
  (the templates carry the client-specific memory policy even with no user
  sources). Files are written read-only (``0444``); a hand-written file without
  our banner is silently backed up to ``<name>.bak`` before the first overwrite.

All ``@<name>/<rest>`` declarations are resolved via `at_paths.resolve_at_path`.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path

from .at_paths import resolve_at_path
from .manifest import Manifest

SKILL_MANIFEST = "SKILL.md"
CLAUDE_DIR = ".claude"
SKILLS_SUBDIR = "skills"
# Holding area inside `.claude/skills/` for pruned skills. Never itself pruned
# (it is the backup target). A declared skill may not use this reserved name.
PRUNED_DIR = ".pruned"

# out filename → template filename (in this package directory).
INSTRUCTION_TEMPLATES = {
    "CLAUDE.md": "CLAUDE_template.md",
    "AGENTS.md": "AGENTS_template.md",
    "GEMINI.md": "GEMINI_template.md",
}
INSERT_MARKER = "<!-- INSERT USER INSTRUCTIONS -->"
# Substring identifying a Duet-generated instruction file (vs hand-written).
GENERATED_BANNER = "AUTO-GENERATED by Duet"

# Backend package dir. The *_template.md files live in packages/instructions
# (alongside bootstrapper.md, agent cores, index.json) and are bundled next to
# the backend at deploy time (electron-builder + copyPlatformInstructions), so at
# deployed runtime they resolve as siblings of server.py. In dev — when running
# against the source tree — they're found via the sibling packages/instructions
# fallback (see _resolve_template).
_BACKEND_DIR = Path(__file__).resolve().parent.parent
# Sibling platform-instructions dir — dev fallback for the templates.
_INSTRUCTIONS_DIR = _BACKEND_DIR.parent / "instructions"


def deploy_instructions(
    context_folder: Path,
    manifest: Manifest,
    repos_path: Path | None,
    context_folders: dict[str, str],
    backend_dir: Path | None = None,
) -> dict:
    """Deploy all instruction components for one context. Idempotent.

    Returns a report: ``{deployed: {...}, warnings: [...]}``.
    """
    backend_dir = backend_dir or _BACKEND_DIR
    warnings: list[str] = []
    deployed: dict = {}

    deployed.update(
        _deploy_skills(context_folder, manifest.skills, repos_path, context_folders, warnings)
    )
    deployed.update(
        _deploy_instruction_files(
            context_folder, manifest.instructions, repos_path, context_folders, backend_dir, warnings
        )
    )
    return {"deployed": deployed, "warnings": warnings}


# =============================================================================
# skills component
# =============================================================================

def _deploy_skills(
    context_folder: Path,
    skills: list[str] | None,
    repos_path: Path | None,
    context_folders: dict[str, str],
    warnings: list[str],
) -> dict:
    # Absent key → don't manage `.claude/skills/` at all.
    if skills is None:
        return {"skills_deployed": [], "skills_pruned": []}

    target_root = context_folder / CLAUDE_DIR / SKILLS_SUBDIR

    to_deploy: list[tuple[str, Path]] = []
    seen: dict[str, str] = {}
    for entry in skills:
        src = resolve_at_path(entry, repos_path, context_folders)
        if src is None:
            warnings.append(f"skills: invalid or unresolvable @-path: {entry}")
            continue
        if not src.is_dir():
            warnings.append(f"skills: not a directory: {entry} ({src})")
            continue
        if not (src / SKILL_MANIFEST).is_file():
            warnings.append(f"skills: missing {SKILL_MANIFEST}: {entry}")
            continue
        name = src.name
        if name == PRUNED_DIR:
            warnings.append(
                f"skills: reserved deploy-name '{PRUNED_DIR}': {entry}; skipping"
            )
            continue
        if name in seen:
            warnings.append(
                f"skills: deploy-name collision '{name}': {entry} would overwrite "
                f"{seen[name]}; skipping"
            )
            continue
        seen[name] = entry
        to_deploy.append((name, src))

    deployed: list[str] = []
    if to_deploy:
        target_root.mkdir(parents=True, exist_ok=True)
        for name, src in to_deploy:
            _mirror_tree_bytes(src, target_root / name)
            deployed.append(name)

    # Prune: any `.claude/skills/<x>` not in the declared set is removed, but
    # backed up first (symmetric with the instructions `.bak`). Backup = move
    # into the `.pruned/` holding area, replacing any earlier backup of the
    # same name with the most recent removed state. `.pruned/` is never pruned.
    pruned: list[str] = []
    if target_root.is_dir():
        keep = {name for name, _ in to_deploy}
        for child in sorted(target_root.iterdir()):
            if child.name == PRUNED_DIR:
                continue
            if child.is_dir() and child.name not in keep:
                backup_root = target_root / PRUNED_DIR
                backup_root.mkdir(parents=True, exist_ok=True)
                dst = backup_root / child.name
                if dst.exists():
                    shutil.rmtree(dst, ignore_errors=True)
                shutil.move(str(child), str(dst))
                pruned.append(child.name)

    return {"skills_deployed": deployed, "skills_pruned": pruned}


def _mirror_tree_bytes(src_dir: Path, dst_dir: Path) -> None:
    """Mirror `src_dir` onto `dst_dir` as raw bytes (binary-safe). Rebuilds the
    destination from scratch so removed source files don't linger."""
    if dst_dir.exists():
        shutil.rmtree(dst_dir, ignore_errors=True)
    dst_dir.mkdir(parents=True, exist_ok=True)
    for path in sorted(src_dir.rglob("*")):
        rel = path.relative_to(src_dir)
        out = dst_dir / rel
        if path.is_dir():
            out.mkdir(parents=True, exist_ok=True)
        elif path.is_file():
            out.write_bytes(path.read_bytes())


# =============================================================================
# instructions component
# =============================================================================

def _deploy_instruction_files(
    context_folder: Path,
    instructions: list[str] | None,
    repos_path: Path | None,
    context_folders: dict[str, str],
    backend_dir: Path,
    warnings: list[str],
) -> dict:
    # Compose the user body from declared @-path sources (order preserved).
    bodies: list[str] = []
    for entry in instructions or []:
        src = resolve_at_path(entry, repos_path, context_folders)
        if src is None or not src.is_file():
            warnings.append(f"instructions: unresolvable or not a file: {entry}")
            continue
        bodies.append(src.read_text(encoding="utf-8").strip())
    user_body = "\n\n".join(bodies)

    # Always generate all three files — the templates carry the memory policy
    # even when there are no user sources.
    written: list[str] = []
    for out_name, tpl_name in INSTRUCTION_TEMPLATES.items():
        tpl = _resolve_template(backend_dir, tpl_name)
        if tpl is None:
            warnings.append(f"instructions: template missing: {tpl_name}")
            continue
        content = tpl.read_text(encoding="utf-8").replace(INSERT_MARKER, user_body)
        _write_managed_file(context_folder / out_name, content, warnings)
        written.append(out_name)

    return {"instructions_written": written}


def _resolve_template(backend_dir: Path, tpl_name: str) -> Path | None:
    """Locate a per-client template.

    At deployed runtime the templates sit next to the backend (bundled from
    packages/instructions). In dev, against the source tree, they live in the
    sibling packages/instructions dir. Returns None if neither exists.
    """
    tpl = backend_dir / tpl_name
    if tpl.is_file():
        return tpl
    tpl = _INSTRUCTIONS_DIR / tpl_name
    return tpl if tpl.is_file() else None


def _write_managed_file(target: Path, content: str, warnings: list[str]) -> None:
    """Write a Duet-managed instruction file read-only (0444).

    If a file already exists WITHOUT our generated banner, it was written by
    hand — silently back it up to ``<name>.bak`` (once) before overwriting.
    """
    if target.exists():
        try:
            existing = target.read_text(encoding="utf-8")
        except OSError:
            existing = ""
        if GENERATED_BANNER not in existing:
            backup = target.with_name(target.name + ".bak")
            if not backup.exists():
                try:
                    backup.write_bytes(target.read_bytes())
                except OSError as e:
                    warnings.append(f"instructions: backup failed for {target.name}: {e}")

    # Write via temp + atomic replace. `os.replace` works over a read-only
    # target on POSIX (directory write permission governs), so no pre-chmod.
    tmp = target.with_name(target.name + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, target)
    os.chmod(target, 0o444)
