import * as path from 'path';
import { FileSystem, nodeFs } from './fs';

export interface WorkspaceFolder {
    path: string;
    name?: string;
}

export interface WorkspaceFile {
    folders: WorkspaceFolder[];
    settings?: Record<string, unknown>;
}

/**
 * Generates `.code-workspace` content for a context that declares one or more
 * git repos (`git_repos` map). Produces N folders pointing at each cloned repo
 * (relative path `../repos/<alias>.git` from the workspaces dir) plus the
 * Drive folder (absolute path).
 *
 * The Drive context folder is always first (primary): it is the project root
 * clients treat as cwd and instruction-files source. The cloned repos follow, in
 * declared alias order, so the multi-root layout is deterministic across
 * machines.
 */
export function generateContextWithReposWorkspace(
    aliases: string[],
    drivePath: string
): WorkspaceFile {
    const repoFolders: WorkspaceFolder[] = aliases.map(alias => ({
        path: path.join('..', 'repos', `${alias}.git`)
    }));
    const driveFolder: WorkspaceFolder = { path: drivePath };
    return { folders: [driveFolder, ...repoFolders] };
}

/**
 * Generates root-contexts.code-workspace content.
 * Lists all root context folders, plus DuetData folder.
 *
 * @param rootContextFolders - Absolute paths to root context folders
 * @param duetDataPath - Absolute path to DuetData directory (added as named folder)
 */
export function generateRootContextsWorkspace(rootContextFolders: string[], duetDataPath?: string): WorkspaceFile {
    const folders: WorkspaceFolder[] = rootContextFolders.map(p => ({ path: p }));
    if (duetDataPath) {
        folders.push({ path: duetDataPath, name: 'DuetData' });
    }
    return { folders };
}

export class WorkspaceManager {
    private readonly fs: FileSystem;

    constructor(
        private readonly workspacesDir: string,
        private readonly reposDir: string,
        fileSystem?: FileSystem
    ) {
        this.fs = fileSystem ?? nodeFs;
    }

    /**
     * Ensures workspaces directory exists.
     */
    async ensureDir(): Promise<void> {
        try {
            await this.fs.access(this.workspacesDir);
        } catch {
            await this.fs.mkdir(this.workspacesDir, { recursive: true });
        }
    }

    /**
     * Gets path to workspace file for a context-with-repos.
     */
    getContextWithReposWorkspacePath(contextName: string): string {
        return path.join(this.workspacesDir, `${contextName}.code-workspace`);
    }

    /**
     * Creates or updates a context-with-repos workspace file.
     * Returns path to the workspace file.
     *
     * Also (re)generates the Kimi Code multi-root workaround
     * (`<drivePath>/.kimi-code/local.toml`) — the workspace file is where the
     * folder set and order are decided, so the workaround belongs to the same
     * write.
     *
     * @param contextName - Context name (e.g., "DuetLab"); used as workspace file basename.
     * @param aliases - `git_repos` keys in declared order; each becomes a folder pointing at `../repos/<alias>.git`.
     * @param drivePath - Absolute path to the context's Drive folder (always the primary/first folder).
     */
    async writeContextWithReposWorkspace(
        contextName: string,
        aliases: string[],
        drivePath: string
    ): Promise<string> {
        await this.ensureDir();

        const workspacePath = this.getContextWithReposWorkspacePath(contextName);
        const workspace = generateContextWithReposWorkspace(aliases, drivePath);
        await this.fs.writeFile(workspacePath, JSON.stringify(workspace, null, 2), 'utf8');

        await this.writeKimiCodeLocalToml(drivePath, aliases);

        return workspacePath;
    }

    /**
     * Kimi Code multi-root workaround.
     *
     * Kimi's VS Code extension is blind to multi-root workspaces — it sees
     * only the primary folder. The documented mechanism to grant it access to
     * the remaining roots is project-local `<project>/.kimi-code/local.toml`
     * with `[workspace] additional_dir` (written interactively by `/add-dir`).
     * Duet generates it alongside the workspace file: the Drive folder is the
     * project root, the cloned repos become `additional_dir` entries
     * (absolute, in declared alias order).
     *
     * Duet-managed: rewritten wholesale on every workspace (re)generation.
     * Absolute machine-specific paths — the file must not be committed.
     */
    private async writeKimiCodeLocalToml(drivePath: string, aliases: string[]): Promise<void> {
        if (aliases.length === 0) {
            return;
        }
        const dir = path.join(drivePath, '.kimi-code');
        await this.fs.mkdir(dir, { recursive: true });
        const dirs = aliases.map(alias => path.join(this.reposDir, `${alias}.git`));
        const content = [
            '# AUTO-GENERATED by Duet · Kimi Code multi-root workaround · do not edit',
            '# Gives Kimi access to the workspace folders beyond the primary one.',
            '# Absolute machine-specific paths — do not commit.',
            '[workspace]',
            `additional_dir = [${dirs.map(d => JSON.stringify(d)).join(', ')}]`,
            ''
        ].join('\n');
        await this.fs.writeFile(path.join(dir, 'local.toml'), content, 'utf8');
    }

    /**
     * Checks if context-with-repos workspace file exists.
     */
    async contextWithReposWorkspaceExists(contextName: string): Promise<boolean> {
        try {
            await this.fs.access(this.getContextWithReposWorkspacePath(contextName));
            return true;
        } catch {
            return false;
        }
    }

    /**
     * Writes root-contexts.code-workspace file.
     *
     * @param rootContextFolders - Absolute paths to root context folders
     * @param outputPath - Path to write workspace file
     * @param duetDataPath - Absolute path to DuetData directory
     */
    async writeRootContextsWorkspace(rootContextFolders: string[], outputPath: string, duetDataPath?: string): Promise<void> {
        const dir = path.dirname(outputPath);
        try {
            await this.fs.access(dir);
        } catch {
            await this.fs.mkdir(dir, { recursive: true });
        }

        const workspace = generateRootContextsWorkspace(rootContextFolders, duetDataPath);
        await this.fs.writeFile(outputPath, JSON.stringify(workspace, null, 2), 'utf8');
    }
}
