import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'fs'
import { join } from 'path'
import { stringify as stringifyToml } from 'smol-toml'
import { createTestContext, type TestContext } from '../../helpers'
import { venvPythonPath } from '../../../src/core/backend'

// Mock os.homedir to use test tmp dir
vi.mock('os', async (importOriginal) => {
  const actual = await importOriginal<typeof import('os')>()
  return {
    ...actual,
    homedir: vi.fn()
  }
})

import { homedir } from 'os'
const mockedHomedir = vi.mocked(homedir)

import {
  configureClaudeCode,
  configureCodex,
  configureAntigravity,
  configureKimi,
  configureClaudeDesktop,
  claudeDesktopConfigDir,
  claudeDesktopDuetServer,
  detectAgents,
  configureAllAgents,
  fixAgentIssue,
  cleanupLegacyClaudeFiles
} from '../../../src/core/ai-clients'

// Test port for MCP URL
const TEST_PORT = 19680
const MCP_URL = `http://127.0.0.1:${TEST_PORT}/mcp`

// Thin session prompt written to DuetData/duet.md (output-style + Codex/Antigravity body).
const SESSION_BODY = '# Duet session prompt\ncore-platform-instructions'
const GENERATED_BODY =
  '<!-- AUTO-GENERATED by Duet from @Duet.git/packages/instructions/bootstrapper.md -->\n# Retired prompt'

function writeSessionPrompt(duetDataDir: string, sessionPrompt = SESSION_BODY): void {
  writeFileSync(join(duetDataDir, 'duet.md'), sessionPrompt, 'utf-8')
}

/** Lays out what a backend deploy leaves for the stdio bridge: venv Python + bridge script. */
function deployBridge(duetDataDir: string): void {
  const python = venvPythonPath(join(duetDataDir, '.venv'))
  mkdirSync(join(python, '..'), { recursive: true })
  writeFileSync(python, '')
  mkdirSync(join(duetDataDir, 'backend'), { recursive: true })
  writeFileSync(join(duetDataDir, 'backend', 'mcp_stdio_bridge.py'), '')
}

/**
 * Reconstructs the on-disk frontmatter that ai-clients.ts produces.
 * Mirrors the production helpers — kept in sync via fresh-content tests.
 */
function expectedOutputStyleFrontmatter(): string {
  // Description is wrapped in single quotes in YAML
  return [
    '---',
    'name: duet-core',
    "description: 'Duet platform instructions: workspace orientation, business context, tools, and knowledge persistence.'",
    'keep-coding-instructions: true',
    '---',
    '',
    ''
  ].join('\n')
}

/**
 * Mirrors production `expectedKimiSystemContent` — thin session body followed
 * by the `${base_prompt}` template variable.
 */
function expectedKimiSystemContent(sessionBody: string): string {
  return sessionBody + '\n\n${base_prompt}\n'
}

// =============================================================================
// TESTS
// =============================================================================

const savedAppData = process.env.APPDATA
const savedXdgConfigHome = process.env.XDG_CONFIG_HOME

function restoreEnv(key: string, value: string | undefined): void {
  if (value === undefined) delete process.env[key]
  else process.env[key] = value
}

describe('core/ai-clients', () => {
  let ctx: TestContext
  let homeDir: string

  beforeEach(() => {
    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue({
        ok: true,
        json: async () => ({ status: 'ok', output_style: 'duet.md', errors: [] })
      })
    )
    ctx = createTestContext()
    homeDir = join(ctx.tmpDir, 'home')
    mkdirSync(homeDir, { recursive: true })
    mockedHomedir.mockReturnValue(homeDir)
    delete process.env.CODEX_HOME
    delete process.env.GEMINI_HOME
    delete process.env.KIMI_CODE_HOME
    // Claude Desktop's config dir hangs off these on Windows / Linux — keep it inside the test home
    process.env.APPDATA = join(homeDir, 'AppData', 'Roaming')
    process.env.XDG_CONFIG_HOME = join(homeDir, '.config')
  })

  afterEach(() => {
    delete process.env.CODEX_HOME
    delete process.env.GEMINI_HOME
    delete process.env.KIMI_CODE_HOME
    restoreEnv('APPDATA', savedAppData)
    restoreEnv('XDG_CONFIG_HOME', savedXdgConfigHome)
    vi.unstubAllGlobals()
    ctx.cleanup()
  })

  // ===========================================================================
  // detectAgents
  // ===========================================================================

  describe('detectAgents', () => {
    it('returns not_found when no agents installed', () => {
      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)

      expect(agents).toHaveLength(5)
      expect(agents[0]).toMatchObject({ id: 'claude-code', status: 'not_found' })
      expect(agents[1]).toMatchObject({ id: 'codex', status: 'not_found' })
      expect(agents[2]).toMatchObject({ id: 'antigravity', status: 'not_found' })
      expect(agents[3]).toMatchObject({ id: 'kimi', status: 'not_found' })
      expect(agents[4]).toMatchObject({ id: 'claude-desktop', status: 'not_found' })
    })

    it('returns needs_setup when ~/.claude exists but not configured', () => {
      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[0]).toMatchObject({ id: 'claude-code', status: 'needs_setup' })
    })

    it('returns needs_setup when ~/.codex exists but not configured', () => {
      mkdirSync(join(homeDir, '.codex'), { recursive: true })
      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[1]).toMatchObject({ id: 'codex', status: 'needs_setup' })
    })

    it('returns needs_setup when ~/.gemini exists but not configured', () => {
      mkdirSync(join(homeDir, '.gemini'), { recursive: true })
      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[2]).toMatchObject({ id: 'antigravity', status: 'needs_setup' })
    })

    it('respects CODEX_HOME env variable', () => {
      const customCodexDir = join(ctx.tmpDir, 'custom-codex')
      mkdirSync(customCodexDir, { recursive: true })
      process.env.CODEX_HOME = customCodexDir

      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[1]).toMatchObject({ id: 'codex', status: 'needs_setup' })
    })

    it('respects GEMINI_HOME env variable', () => {
      const customGeminiDir = join(ctx.tmpDir, 'custom-gemini')
      mkdirSync(customGeminiDir, { recursive: true })
      process.env.GEMINI_HOME = customGeminiDir

      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[2]).toMatchObject({ id: 'antigravity', status: 'needs_setup' })
    })

    it('returns needs_setup when ~/.kimi-code exists but not configured', () => {
      mkdirSync(join(homeDir, '.kimi-code'), { recursive: true })
      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[3]).toMatchObject({ id: 'kimi', status: 'needs_setup' })
    })

    it('respects KIMI_CODE_HOME env variable', () => {
      const customKimiDir = join(ctx.tmpDir, 'custom-kimi')
      mkdirSync(customKimiDir, { recursive: true })
      process.env.KIMI_CODE_HOME = customKimiDir

      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[3]).toMatchObject({ id: 'kimi', status: 'needs_setup' })
    })

    // --- H1: Claude full happy path ---
    it('returns configured for Claude Code when output-style + settings + MCP match without custom agents', () => {
      writeSessionPrompt(ctx.duetDataDir)

      const stylesDir = join(homeDir, '.claude', 'output-styles')
      const agentsDir = join(homeDir, '.claude', 'agents')
      mkdirSync(stylesDir, { recursive: true })
      mkdirSync(agentsDir, { recursive: true })

      writeFileSync(
        join(stylesDir, 'duet-core.md'),
        expectedOutputStyleFrontmatter() + SESSION_BODY
      )
      writeFileSync(
        join(homeDir, '.claude', 'settings.json'),
        JSON.stringify({ outputStyle: 'duet-core' })
      )
      writeFileSync(
        join(homeDir, '.claude.json'),
        JSON.stringify({ mcpServers: { duet: { type: 'http', url: MCP_URL } } })
      )

      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)

      expect(agents[0]).toMatchObject({ id: 'claude-code', status: 'configured' })
      expect(agents[0].checkedFiles).toBeDefined()
      expect(agents[0].checkedFiles!.every((f) => f.ok)).toBe(true)
      // Only the platform style, settings, and MCP configuration are required.
      expect(agents[0].checkedFiles).toHaveLength(3)
    })

    // --- H4b: stale frontmatter (body intact) ---
    it('detects stale frontmatter (body intact)', () => {
      writeSessionPrompt(ctx.duetDataDir)

      const stylesDir = join(homeDir, '.claude', 'output-styles')
      const agentsDir = join(homeDir, '.claude', 'agents')
      mkdirSync(stylesDir, { recursive: true })
      mkdirSync(agentsDir, { recursive: true })

      // Old-style frontmatter (`name: Duet` from pre-migration) but with the
      // current session body — body matches, frontmatter doesn't.
      writeFileSync(
        join(stylesDir, 'duet-core.md'),
        '---\nname: Duet\ndescription: old\nkeep-coding-instructions: true\n---\n\n' + SESSION_BODY
      )
      writeFileSync(
        join(homeDir, '.claude', 'settings.json'),
        JSON.stringify({ outputStyle: 'duet-core' })
      )
      writeFileSync(
        join(homeDir, '.claude.json'),
        JSON.stringify({ mcpServers: { duet: { type: 'http', url: MCP_URL } } })
      )

      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      const claude = agents[0]
      expect(claude.status).toBe('needs_setup')
      const styleFile = claude.checkedFiles!.find((f) =>
        f.path.endsWith(join('output-styles', 'duet-core.md'))
      )
      expect(styleFile?.ok).toBe(false)
    })

    it('returns needs_setup for Claude Code when only MCP exists', () => {
      writeSessionPrompt(ctx.duetDataDir)
      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      writeFileSync(
        join(homeDir, '.claude.json'),
        JSON.stringify({ mcpServers: { duet: { type: 'http', url: MCP_URL } } })
      )

      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[0]).toMatchObject({ id: 'claude-code', status: 'needs_setup' })
      expect(agents[0].details).toContain('MCP настроен')
    })

    it('returns configured for Codex when config.toml has MCP + instructions and content matches', () => {
      writeSessionPrompt(ctx.duetDataDir)

      const codexDir = join(homeDir, '.codex')
      const instructionsPath = join(codexDir, 'duet_instructions.md')
      mkdirSync(codexDir, { recursive: true })
      writeFileSync(instructionsPath, SESSION_BODY)
      writeFileSync(
        join(codexDir, 'config.toml'),
        stringifyToml({
          model_instructions_file: instructionsPath,
          mcp_servers: { duet: { url: MCP_URL } }
        }) + '\n'
      )

      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[1]).toMatchObject({ id: 'codex', status: 'configured' })
    })

    it('returns needs_setup for Codex when only MCP configured', () => {
      writeSessionPrompt(ctx.duetDataDir)

      const codexDir = join(homeDir, '.codex')
      mkdirSync(codexDir, { recursive: true })
      writeFileSync(
        join(codexDir, 'config.toml'),
        stringifyToml({ mcp_servers: { duet: { url: MCP_URL } } }) + '\n'
      )

      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[1]).toMatchObject({ id: 'codex', status: 'needs_setup' })
      expect(agents[1].details).toContain('MCP настроен')
    })

    it('returns configured for Antigravity when GEMINI.md + MCP exist and content matches', () => {
      writeSessionPrompt(ctx.duetDataDir)

      const geminiDir = join(homeDir, '.gemini')
      mkdirSync(join(geminiDir, 'antigravity'), { recursive: true })
      writeFileSync(join(geminiDir, 'GEMINI.md'), SESSION_BODY)
      writeFileSync(
        join(geminiDir, 'antigravity', 'mcp_config.json'),
        JSON.stringify({ mcpServers: { duet: { type: 'http', serverURL: MCP_URL } } })
      )

      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[2]).toMatchObject({ id: 'antigravity', status: 'configured' })
      expect(agents[2].checkedFiles).toBeDefined()
      expect(agents[2].checkedFiles!.every((f) => f.ok)).toBe(true)
    })

    it('returns configured for Kimi when SYSTEM.md + MCP exist and content matches', () => {
      writeSessionPrompt(ctx.duetDataDir)

      const kimiDir = join(homeDir, '.kimi-code')
      mkdirSync(kimiDir, { recursive: true })
      writeFileSync(join(kimiDir, 'SYSTEM.md'), expectedKimiSystemContent(SESSION_BODY))
      writeFileSync(
        join(kimiDir, 'mcp.json'),
        JSON.stringify({ mcpServers: { duet: { url: MCP_URL } } })
      )

      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[3]).toMatchObject({ id: 'kimi', status: 'configured' })
      expect(agents[3].checkedFiles).toBeDefined()
      expect(agents[3].checkedFiles!.every((f) => f.ok)).toBe(true)
    })

    it('returns needs_setup for Kimi when only MCP configured', () => {
      writeSessionPrompt(ctx.duetDataDir)

      const kimiDir = join(homeDir, '.kimi-code')
      mkdirSync(kimiDir, { recursive: true })
      writeFileSync(
        join(kimiDir, 'mcp.json'),
        JSON.stringify({ mcpServers: { duet: { url: MCP_URL } } })
      )

      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[3]).toMatchObject({ id: 'kimi', status: 'needs_setup' })
      expect(agents[3].details).toContain('MCP настроен')
    })

    // --- H1 / H7: round-trip detect after configure ---
    it('detect after configure returns configured (round-trip, idempotent)', async () => {
      writeSessionPrompt(ctx.duetDataDir)

      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      mkdirSync(join(homeDir, '.codex'), { recursive: true })
      mkdirSync(join(homeDir, '.gemini'), { recursive: true })
      mkdirSync(join(homeDir, '.kimi-code'), { recursive: true })

      // First configure. configureAllAgents now triggers a merge first (HTTP); no
      // backend in tests → triggerMerge degrades gracefully and the pre-seeded
      // duet-*.md files on disk are used as-is.
      const r1 = await configureAllAgents(ctx.duetDataDir, TEST_PORT)
      expect(r1[0].status).toBe('configured')
      expect(r1[1].status).toBe('configured')
      expect(r1[2].status).toBe('configured')
      expect(r1[3].status).toBe('configured')

      // Second configure (idempotency)
      const r2 = await configureAllAgents(ctx.duetDataDir, TEST_PORT)
      expect(r2[0].status).toBe('configured')
      expect(r2[1].status).toBe('configured')
      expect(r2[2].status).toBe('configured')
      expect(r2[3].status).toBe('configured')

      // Detect agrees
      const detect = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(detect[0].status).toBe('configured')
      expect(detect[1].status).toBe('configured')
      expect(detect[2].status).toBe('configured')
      expect(detect[3].status).toBe('configured')
    })

    // --- H13: detect when merged content is null (merge never ran) ---
    it('claude detect with no merged content returns needs_setup without crashing', () => {
      // No DuetData/duet-*.md files

      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[0].status).toBe('needs_setup')
      // Should not crash
    })
  })

  // ===========================================================================
  // configureClaudeCode
  // ===========================================================================

  describe('configureClaudeCode', () => {
    it.each(['duet', 'duet-executor'])('migrates the generated %s style to duet-core', (name) => {
      writeSessionPrompt(ctx.duetDataDir)
      const styles = join(homeDir, '.claude', 'output-styles')
      mkdirSync(styles, { recursive: true })
      const previous = join(styles, `${name}.md`)
      writeFileSync(previous, `---\nname: ${name}\n---\n${GENERATED_BODY}`)
      const settings = join(homeDir, '.claude', 'settings.json')
      writeFileSync(
        settings,
        JSON.stringify({ outputStyle: name, permissions: { allow: ['Read'] } })
      )

      expect(configureClaudeCode(SESSION_BODY, ctx.duetDataDir, TEST_PORT).status).toBe(
        'configured'
      )
      expect(existsSync(previous)).toBe(false)
      expect(readFileSync(join(styles, 'duet-core.md'), 'utf-8')).toBe(
        expectedOutputStyleFrontmatter() + SESSION_BODY
      )
      expect(JSON.parse(readFileSync(settings, 'utf-8'))).toEqual({
        outputStyle: 'duet-core',
        permissions: { allow: ['Read'] }
      })
      expect(detectAgents(ctx.duetDataDir, TEST_PORT)[0].status).toBe('configured')
      expect(cleanupLegacyClaudeFiles(ctx.duetDataDir)).toEqual({ removed: [], failed: [] })
    })

    it('writes the shared style without creating a custom agent directory', () => {
      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      expect(configureClaudeCode(SESSION_BODY, ctx.duetDataDir, TEST_PORT).status).toBe(
        'configured'
      )
      expect(readFileSync(join(homeDir, '.claude', 'output-styles', 'duet-core.md'), 'utf-8')).toBe(
        expectedOutputStyleFrontmatter() + SESSION_BODY
      )
      expect(existsSync(join(homeDir, '.claude', 'agents'))).toBe(false)
    })

    it('returns not_found when ~/.claude does not exist', () => {
      const result = configureClaudeCode(null, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('not_found')
      expect(result.id).toBe('claude-code')
    })

    it('returns needs_setup when merged content is null', () => {
      mkdirSync(join(homeDir, '.claude'), { recursive: true })

      const result = configureClaudeCode(null, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('needs_setup')
      expect(result.details).toContain('not been generated')

      // MCP should still be written
      const claudeJsonPath = join(homeDir, '.claude.json')
      expect(existsSync(claudeJsonPath)).toBe(true)
      const config = JSON.parse(readFileSync(claudeJsonPath, 'utf-8'))
      expect(config.mcpServers.duet).toBeDefined()
    })

    // --- H6: outputStyle migrates from "Duet" to "duet-core" ---
    it('migrates outputStyle from old "Duet" to "duet-core"', () => {
      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      writeFileSync(
        join(homeDir, '.claude', 'settings.json'),
        JSON.stringify({ outputStyle: 'Duet', permissions: { allow: ['Edit'] } })
      )

      configureClaudeCode(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const config = JSON.parse(readFileSync(join(homeDir, '.claude', 'settings.json'), 'utf-8'))
      expect(config.outputStyle).toBe('duet-core')
      // Other keys preserved
      expect(config.permissions).toEqual({ allow: ['Edit'] })
    })

    it('writes outputStyle "duet-core" to ~/.claude/settings.json', () => {
      mkdirSync(join(homeDir, '.claude'), { recursive: true })

      configureClaudeCode(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const settingsPath = join(homeDir, '.claude', 'settings.json')
      expect(existsSync(settingsPath)).toBe(true)
      const config = JSON.parse(readFileSync(settingsPath, 'utf-8'))
      expect(config.outputStyle).toBe('duet-core')
    })

    it('preserves existing keys in ~/.claude/settings.json', () => {
      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      writeFileSync(
        join(homeDir, '.claude', 'settings.json'),
        JSON.stringify({ permissions: { allow: ['Edit'] } })
      )

      configureClaudeCode(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const config = JSON.parse(readFileSync(join(homeDir, '.claude', 'settings.json'), 'utf-8'))
      expect(config.outputStyle).toBe('duet-core')
      expect(config.permissions).toEqual({ allow: ['Edit'] })
    })

    it('writes HTTP MCP config to ~/.claude.json', () => {
      mkdirSync(join(homeDir, '.claude'), { recursive: true })

      configureClaudeCode(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const claudeJsonPath = join(homeDir, '.claude.json')
      expect(existsSync(claudeJsonPath)).toBe(true)

      const config = JSON.parse(readFileSync(claudeJsonPath, 'utf-8'))
      expect(config.mcpServers).toBeDefined()
      expect(config.mcpServers.duet).toBeDefined()
      expect(config.mcpServers.duet.type).toBe('http')
      expect(config.mcpServers.duet.url).toBe(MCP_URL)
    })

    it('preserves existing MCP entries when adding duet', () => {
      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      const claudeJsonPath = join(homeDir, '.claude.json')
      writeFileSync(
        claudeJsonPath,
        JSON.stringify({
          mcpServers: { 'ai-kit': { command: 'python', args: ['server.py'] } }
        })
      )

      configureClaudeCode(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const config = JSON.parse(readFileSync(claudeJsonPath, 'utf-8'))
      expect(config.mcpServers['ai-kit']).toBeDefined()
      expect(config.mcpServers.duet).toBeDefined()
    })

    it('preserves existing keys in ~/.claude.json', () => {
      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      const claudeJsonPath = join(homeDir, '.claude.json')
      writeFileSync(
        claudeJsonPath,
        JSON.stringify({
          existingKey: 'keep-me',
          mcpServers: { other: { command: 'other-cmd' } }
        })
      )

      configureClaudeCode(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const config = JSON.parse(readFileSync(claudeJsonPath, 'utf-8'))
      expect(config.existingKey).toBe('keep-me')
      expect(config.mcpServers.other).toBeDefined()
      expect(config.mcpServers.duet).toBeDefined()
    })

    it('handles invalid JSON in ~/.claude.json gracefully', () => {
      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      writeFileSync(join(homeDir, '.claude.json'), 'not json {{{')

      const result = configureClaudeCode(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('configured')
      const config = JSON.parse(readFileSync(join(homeDir, '.claude.json'), 'utf-8'))
      expect(config.mcpServers.duet).toBeDefined()
    })

    // --- Migration: configure auto-clears legacy artifacts after writing new files ---

    // --- Migration: legacy uborka does NOT run when configure fails (no merged content) ---
    it('does NOT remove legacy files if merged content is null (configure not configured)', () => {
      mkdirSync(join(homeDir, '.claude', 'output-styles'), { recursive: true })
      mkdirSync(join(homeDir, '.claude', 'agents'), { recursive: true })

      const legacyStyle = join(homeDir, '.claude', 'output-styles', 'duet.md')
      writeFileSync(legacyStyle, '# legacy')

      const result = configureClaudeCode(null, ctx.duetDataDir, TEST_PORT)
      expect(result.status).toBe('needs_setup')
      // Legacy preserved — uborka must not run on partial migration
      expect(existsSync(legacyStyle)).toBe(true)
    })

    // --- Migration: does NOT touch user's personal vizir.md during configure ---
    it('preserves user-personal ~/.claude/agents/vizir.md during configure', () => {
      mkdirSync(join(homeDir, '.claude', 'agents'), { recursive: true })
      const userVizir = join(homeDir, '.claude', 'agents', 'vizir.md')
      writeFileSync(userVizir, '# user content — keep me')

      configureClaudeCode(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      expect(existsSync(userVizir)).toBe(true)
      expect(readFileSync(userVizir, 'utf-8')).toBe('# user content — keep me')
    })
  })

  // ===========================================================================
  // configureCodex
  // ===========================================================================

  describe('configureCodex', () => {
    it('returns not_found when ~/.codex does not exist', () => {
      const result = configureCodex(null, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('not_found')
      expect(result.id).toBe('codex')
    })

    it('returns needs_setup when session prompt is null', () => {
      mkdirSync(join(homeDir, '.codex'), { recursive: true })

      const result = configureCodex(null, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('needs_setup')
      expect(result.details).toContain('не сгенерированы')

      const configPath = join(homeDir, '.codex', 'config.toml')
      expect(existsSync(configPath)).toBe(true)
      const content = readFileSync(configPath, 'utf-8')
      expect(content).toContain('[mcp_servers.duet]')
      expect(content).not.toContain('model_instructions_file')
    })

    it('configures config.toml and writes instructions when ~/.codex exists', () => {
      mkdirSync(join(homeDir, '.codex'), { recursive: true })

      const result = configureCodex(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('configured')

      const configPath = join(homeDir, '.codex', 'config.toml')
      expect(existsSync(configPath)).toBe(true)

      const content = readFileSync(configPath, 'utf-8')
      expect(content).toContain('model_instructions_file')
      expect(content).toContain('duet_instructions.md')

      const instructionsPath = join(homeDir, '.codex', 'duet_instructions.md')
      expect(existsSync(instructionsPath)).toBe(true)
      expect(readFileSync(instructionsPath, 'utf-8')).toBe(SESSION_BODY)
    })

    it('adds HTTP MCP section to config.toml', () => {
      mkdirSync(join(homeDir, '.codex'), { recursive: true })

      configureCodex(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const content = readFileSync(join(homeDir, '.codex', 'config.toml'), 'utf-8')
      expect(content).toContain('[mcp_servers.duet]')
      expect(content).toContain(`url = "${MCP_URL}"`)
    })

    it('preserves existing config.toml content', () => {
      const codexDir = join(homeDir, '.codex')
      mkdirSync(codexDir, { recursive: true })
      writeFileSync(join(codexDir, 'config.toml'), 'model = "o3"\n')

      configureCodex(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const content = readFileSync(join(codexDir, 'config.toml'), 'utf-8')
      expect(content).toContain('model = "o3"')
      expect(content).toContain('model_instructions_file')
      expect(content).toContain('[mcp_servers.duet]')
    })

    it('updates existing model_instructions_file value', () => {
      const codexDir = join(homeDir, '.codex')
      mkdirSync(codexDir, { recursive: true })
      writeFileSync(join(codexDir, 'config.toml'), 'model_instructions_file = "/old/path"\n')

      configureCodex(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const content = readFileSync(join(codexDir, 'config.toml'), 'utf-8')
      expect(content).not.toContain('/old/path')
      expect(content).toContain('duet_instructions.md')
    })

    it('updates existing [mcp_servers.duet] section', () => {
      const codexDir = join(homeDir, '.codex')
      mkdirSync(codexDir, { recursive: true })
      writeFileSync(
        join(codexDir, 'config.toml'),
        '[mcp_servers.duet]\ncommand = "old-command"\nargs = ["old"]\n'
      )

      configureCodex(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const content = readFileSync(join(codexDir, 'config.toml'), 'utf-8')
      expect(content).not.toContain('old-command')
      expect(content).toContain(`url = "${MCP_URL}"`)
    })

    it('migrates legacy [mcp.duet] to [mcp_servers.duet]', () => {
      const codexDir = join(homeDir, '.codex')
      mkdirSync(codexDir, { recursive: true })
      writeFileSync(
        join(codexDir, 'config.toml'),
        'model = "o3"\n\n[mcp.duet]\ncommand = "old-command"\nargs = ["old"]\n'
      )

      configureCodex(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const content = readFileSync(join(codexDir, 'config.toml'), 'utf-8')
      expect(content).not.toContain('[mcp.duet]')
      expect(content).toContain('[mcp_servers.duet]')
      expect(content).toContain(`url = "${MCP_URL}"`)
      expect(content).toContain('model = "o3"')
    })

    it('handles config starting with a section (no root keys)', () => {
      const codexDir = join(homeDir, '.codex')
      mkdirSync(codexDir, { recursive: true })
      writeFileSync(join(codexDir, 'config.toml'), '[mcp_servers.other]\ncommand = "other-cmd"\n')

      configureCodex(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const content = readFileSync(join(codexDir, 'config.toml'), 'utf-8')
      expect(content).toContain('[mcp_servers.duet]')
      expect(content).toContain('[mcp_servers.other]')
      expect(content).toContain('command = "other-cmd"')
      expect(content).toContain('model_instructions_file')
    })

    it('handles args with square brackets correctly', () => {
      const codexDir = join(homeDir, '.codex')
      mkdirSync(codexDir, { recursive: true })
      writeFileSync(
        join(codexDir, 'config.toml'),
        '[mcp_servers.duet]\ncommand = "old"\nargs = ["old-server.js", "--data-dir", "/old/path"]\n\n[mcp_servers.other]\ncommand = "keep-me"\n'
      )

      configureCodex(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const content = readFileSync(join(codexDir, 'config.toml'), 'utf-8')
      expect(content).not.toContain('old-server.js')
      expect(content).toContain(`url = "${MCP_URL}"`)
      expect(content).toContain('[mcp_servers.other]')
      expect(content).toContain('command = "keep-me"')
    })

    it('produces valid TOML parseable by smol-toml', async () => {
      const codexDir = join(homeDir, '.codex')
      mkdirSync(codexDir, { recursive: true })

      configureCodex(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const content = readFileSync(join(codexDir, 'config.toml'), 'utf-8')
      const { parse } = await import('smol-toml')
      const parsed = parse(content)
      expect(parsed.mcp_servers).toBeDefined()
      expect((parsed.mcp_servers as Record<string, Record<string, string>>).duet.url).toBe(MCP_URL)
      expect(parsed.model_instructions_file).toContain('duet_instructions.md')
    })

    it('respects CODEX_HOME env variable', () => {
      const customCodexDir = join(ctx.tmpDir, 'custom-codex')
      mkdirSync(customCodexDir, { recursive: true })
      process.env.CODEX_HOME = customCodexDir

      const result = configureCodex(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('configured')
      expect(existsSync(join(customCodexDir, 'config.toml'))).toBe(true)
    })

    // --- H8: no codex/agents/ directory created ---
    it('does NOT write any custom agent files in ~/.codex/agents/', () => {
      mkdirSync(join(homeDir, '.codex'), { recursive: true })

      configureCodex(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const codexAgentsDir = join(homeDir, '.codex', 'agents')
      expect(existsSync(codexAgentsDir)).toBe(false)
    })
  })

  // ===========================================================================
  // configureAntigravity
  // ===========================================================================

  describe('configureAntigravity', () => {
    it('returns not_found when ~/.gemini does not exist', () => {
      const result = configureAntigravity(null, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('not_found')
      expect(result.id).toBe('antigravity')
    })

    it('returns needs_setup when session prompt is null', () => {
      mkdirSync(join(homeDir, '.gemini'), { recursive: true })

      const result = configureAntigravity(null, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('needs_setup')
      expect(result.details).toContain('не сгенерированы')

      const mcpPath = join(homeDir, '.gemini', 'antigravity', 'mcp_config.json')
      expect(existsSync(mcpPath)).toBe(true)
      const config = JSON.parse(readFileSync(mcpPath, 'utf-8'))
      expect(config.mcpServers.duet).toBeDefined()
    })

    it('configures GEMINI.md and MCP when ~/.gemini exists', () => {
      mkdirSync(join(homeDir, '.gemini'), { recursive: true })

      const result = configureAntigravity(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('configured')

      const instructionsPath = join(homeDir, '.gemini', 'GEMINI.md')
      expect(existsSync(instructionsPath)).toBe(true)
      expect(readFileSync(instructionsPath, 'utf-8')).toBe(SESSION_BODY)

      const mcpPath = join(homeDir, '.gemini', 'antigravity', 'mcp_config.json')
      expect(existsSync(mcpPath)).toBe(true)
      const mcpConfig = JSON.parse(readFileSync(mcpPath, 'utf-8'))
      expect(mcpConfig.mcpServers.duet.type).toBe('http')
      expect(mcpConfig.mcpServers.duet.serverURL).toBe(MCP_URL)
    })

    it('preserves existing keys in mcp_config.json', () => {
      const geminiDir = join(homeDir, '.gemini')
      mkdirSync(join(geminiDir, 'antigravity'), { recursive: true })
      writeFileSync(
        join(geminiDir, 'antigravity', 'mcp_config.json'),
        JSON.stringify({
          existingKey: 'keep',
          mcpServers: { other: { command: 'other' } }
        })
      )

      configureAntigravity(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const config = JSON.parse(
        readFileSync(join(geminiDir, 'antigravity', 'mcp_config.json'), 'utf-8')
      )
      expect(config.existingKey).toBe('keep')
      expect(config.mcpServers.other).toBeDefined()
      expect(config.mcpServers.duet).toBeDefined()
    })

    it('respects GEMINI_HOME env variable', () => {
      const customGeminiDir = join(ctx.tmpDir, 'custom-gemini')
      mkdirSync(customGeminiDir, { recursive: true })
      process.env.GEMINI_HOME = customGeminiDir

      const result = configureAntigravity(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('configured')
      expect(existsSync(join(customGeminiDir, 'GEMINI.md'))).toBe(true)
    })

    // --- H9: no gemini/agents/ directory created ---
    it('does NOT write any custom agent files in ~/.gemini/', () => {
      mkdirSync(join(homeDir, '.gemini'), { recursive: true })

      configureAntigravity(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const geminiAgentsDir = join(homeDir, '.gemini', 'agents')
      expect(existsSync(geminiAgentsDir)).toBe(false)
    })
  })

  // ===========================================================================
  // configureKimi
  // ===========================================================================

  describe('configureKimi', () => {
    it('returns not_found when ~/.kimi-code does not exist', () => {
      const result = configureKimi(null, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('not_found')
      expect(result.id).toBe('kimi')
    })

    it('returns needs_setup when session content is null', () => {
      mkdirSync(join(homeDir, '.kimi-code'), { recursive: true })

      const result = configureKimi(null, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('needs_setup')
      expect(result.details).toContain('не сгенерированы')

      const mcpPath = join(homeDir, '.kimi-code', 'mcp.json')
      expect(existsSync(mcpPath)).toBe(true)
      const config = JSON.parse(readFileSync(mcpPath, 'utf-8'))
      expect(config.mcpServers.duet).toBeDefined()
    })

    it('configures SYSTEM.md and MCP when ~/.kimi-code exists', () => {
      mkdirSync(join(homeDir, '.kimi-code'), { recursive: true })

      const result = configureKimi(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('configured')

      const instructionsPath = join(homeDir, '.kimi-code', 'SYSTEM.md')
      expect(existsSync(instructionsPath)).toBe(true)
      expect(readFileSync(instructionsPath, 'utf-8')).toBe(expectedKimiSystemContent(SESSION_BODY))

      const mcpPath = join(homeDir, '.kimi-code', 'mcp.json')
      expect(existsSync(mcpPath)).toBe(true)
      const mcpConfig = JSON.parse(readFileSync(mcpPath, 'utf-8'))
      expect(mcpConfig.mcpServers.duet.url).toBe(MCP_URL)
      // Kimi contract: no `type` field — a `url` entry implies HTTP transport
      expect(mcpConfig.mcpServers.duet.type).toBeUndefined()
    })

    it('preserves existing keys in mcp.json', () => {
      const kimiDir = join(homeDir, '.kimi-code')
      mkdirSync(kimiDir, { recursive: true })
      writeFileSync(
        join(kimiDir, 'mcp.json'),
        JSON.stringify({
          existingKey: 'keep',
          mcpServers: { other: { command: 'other' } }
        })
      )

      configureKimi(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const config = JSON.parse(readFileSync(join(kimiDir, 'mcp.json'), 'utf-8'))
      expect(config.existingKey).toBe('keep')
      expect(config.mcpServers.other).toBeDefined()
      expect(config.mcpServers.duet).toBeDefined()
    })

    it('handles invalid JSON in mcp.json gracefully', () => {
      const kimiDir = join(homeDir, '.kimi-code')
      mkdirSync(kimiDir, { recursive: true })
      writeFileSync(join(kimiDir, 'mcp.json'), 'not json {{{')

      const result = configureKimi(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('configured')
      const config = JSON.parse(readFileSync(join(kimiDir, 'mcp.json'), 'utf-8'))
      expect(config.mcpServers.duet).toBeDefined()
    })

    it('respects KIMI_CODE_HOME env variable', () => {
      const customKimiDir = join(ctx.tmpDir, 'custom-kimi')
      mkdirSync(customKimiDir, { recursive: true })
      process.env.KIMI_CODE_HOME = customKimiDir

      const result = configureKimi(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('configured')
      expect(existsSync(join(customKimiDir, 'SYSTEM.md'))).toBe(true)
    })

    it('does NOT write any custom agent files in ~/.kimi-code/agents/', () => {
      mkdirSync(join(homeDir, '.kimi-code'), { recursive: true })

      configureKimi(SESSION_BODY, ctx.duetDataDir, TEST_PORT)

      const kimiAgentsDir = join(homeDir, '.kimi-code', 'agents')
      expect(existsSync(kimiAgentsDir)).toBe(false)
    })
  })

  // ===========================================================================
  // configureClaudeDesktop
  // ===========================================================================

  describe('claudeDesktopConfigDir', () => {
    it('uses Application Support on macOS', () => {
      expect(claudeDesktopConfigDir('darwin', {}, '/Users/u')).toBe(
        join('/Users/u', 'Library', 'Application Support', 'Claude')
      )
    })

    it('uses %APPDATA% on Windows, falling back to AppData/Roaming', () => {
      expect(
        claudeDesktopConfigDir('win32', { APPDATA: 'C:/Users/u/AppData/Roaming' }, 'C:/Users/u')
      ).toBe(join('C:/Users/u/AppData/Roaming', 'Claude'))
      expect(claudeDesktopConfigDir('win32', {}, 'C:/Users/u')).toBe(
        join('C:/Users/u', 'AppData', 'Roaming', 'Claude')
      )
    })

    it('uses XDG_CONFIG_HOME on Linux, falling back to ~/.config', () => {
      expect(claudeDesktopConfigDir('linux', { XDG_CONFIG_HOME: '/x' }, '/home/u')).toBe(
        join('/x', 'Claude')
      )
      expect(claudeDesktopConfigDir('linux', {}, '/home/u')).toBe(
        join('/home/u', '.config', 'Claude')
      )
    })
  })

  describe('claudeDesktopDuetServer', () => {
    it('runs the bridge with the venv Python and the slash-terminated MCP URL', () => {
      expect(claudeDesktopDuetServer('/data', TEST_PORT, 'darwin')).toEqual({
        command: join('/data', '.venv', 'bin', 'python3'),
        args: [join('/data', 'backend', 'mcp_stdio_bridge.py'), `${MCP_URL}/`]
      })
    })

    it('uses Scripts/python.exe on Windows', () => {
      expect(claudeDesktopDuetServer('/data', TEST_PORT, 'win32').command).toBe(
        join('/data', '.venv', 'Scripts', 'python.exe')
      )
    })
  })

  describe('configureClaudeDesktop', () => {
    const configPath = (): string => join(claudeDesktopConfigDir(), 'claude_desktop_config.json')
    interface DesktopConfig {
      preferences?: unknown
      mcpServers: Record<string, unknown>
    }
    const readConfig = (): DesktopConfig => JSON.parse(readFileSync(configPath(), 'utf-8'))
    const expectedServer = (): ReturnType<typeof claudeDesktopDuetServer> =>
      claudeDesktopDuetServer(ctx.duetDataDir, TEST_PORT)

    it('returns not_found and writes nothing when Claude Desktop is not installed', () => {
      const result = configureClaudeDesktop(ctx.duetDataDir, TEST_PORT)

      expect(result).toMatchObject({ id: 'claude-desktop', status: 'not_found' })
      expect(existsSync(claudeDesktopConfigDir())).toBe(false)
    })

    it('creates the config with the duet stdio server and asks for a restart', () => {
      mkdirSync(claudeDesktopConfigDir(), { recursive: true })
      deployBridge(ctx.duetDataDir)

      const result = configureClaudeDesktop(ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('configured')
      expect(result.details).toContain('Перезапустите Claude Desktop')
      expect(readConfig().mcpServers.duet).toEqual(expectedServer())
    })

    it('keeps Desktop preferences and other MCP servers', () => {
      mkdirSync(claudeDesktopConfigDir(), { recursive: true })
      writeFileSync(
        configPath(),
        JSON.stringify({
          preferences: { sidebarMode: 'chat', trusted: ['/Users/u/Мой Диск'] },
          mcpServers: { other: { command: 'other', args: ['x'] } }
        })
      )

      configureClaudeDesktop(ctx.duetDataDir, TEST_PORT)

      const config = readConfig()
      expect(config.preferences).toEqual({ sidebarMode: 'chat', trusted: ['/Users/u/Мой Диск'] })
      expect(config.mcpServers.other).toEqual({ command: 'other', args: ['x'] })
      expect(config.mcpServers.duet).toEqual(expectedServer())
    })

    it('replaces a hand-written npx entry', () => {
      mkdirSync(claudeDesktopConfigDir(), { recursive: true })
      writeFileSync(
        configPath(),
        JSON.stringify({
          mcpServers: { duet: { command: 'npx', args: ['-y', 'mcp-remote', `${MCP_URL}/`] } }
        })
      )

      configureClaudeDesktop(ctx.duetDataDir, TEST_PORT)

      expect(readConfig().mcpServers.duet).toEqual(expectedServer())
    })

    it('does not rewrite the file when the entry already matches', () => {
      mkdirSync(claudeDesktopConfigDir(), { recursive: true })
      deployBridge(ctx.duetDataDir)
      const compact = JSON.stringify({ a: 1, mcpServers: { duet: expectedServer() } })
      writeFileSync(configPath(), compact)

      const result = configureClaudeDesktop(ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('configured')
      expect(readFileSync(configPath(), 'utf-8')).toBe(compact)
    })

    it('leaves an unreadable config untouched', () => {
      mkdirSync(claudeDesktopConfigDir(), { recursive: true })
      writeFileSync(configPath(), 'not json {{{')

      const result = configureClaudeDesktop(ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('needs_setup')
      expect(result.details).toContain('не читается')
      expect(readFileSync(configPath(), 'utf-8')).toBe('not json {{{')
    })

    it('reports needs_setup while the backend (venv + bridge) is not deployed', () => {
      mkdirSync(claudeDesktopConfigDir(), { recursive: true })

      const result = configureClaudeDesktop(ctx.duetDataDir, TEST_PORT)

      expect(result.status).toBe('needs_setup')
      expect(result.details).toContain('деплой')
      expect(readConfig().mcpServers.duet).toEqual(expectedServer())
      expect(result.checkedFiles?.map((f) => f.ok)).toEqual([true, false, false])
    })

    it('detect agrees with configure (round-trip)', () => {
      mkdirSync(claudeDesktopConfigDir(), { recursive: true })
      deployBridge(ctx.duetDataDir)

      const configured = configureClaudeDesktop(ctx.duetDataDir, TEST_PORT)
      const detected = detectAgents(ctx.duetDataDir, TEST_PORT)[4]

      expect(detected.status).toBe(configured.status)
      expect(detected.checkedFiles).toEqual(configured.checkedFiles)
    })

    it('detect flags a duet entry that points at another port', () => {
      mkdirSync(claudeDesktopConfigDir(), { recursive: true })
      deployBridge(ctx.duetDataDir)
      configureClaudeDesktop(ctx.duetDataDir, TEST_PORT + 1)

      const detected = detectAgents(ctx.duetDataDir, TEST_PORT)[4]

      expect(detected.status).toBe('needs_setup')
      expect(detected.checkedFiles?.[0].ok).toBe(false)
    })
  })

  // ===========================================================================
  // additionalDirectories check
  // ===========================================================================

  describe('additionalDirectories detection', () => {
    it('detects additionalDirectories in Claude Code settings', () => {
      writeSessionPrompt(ctx.duetDataDir)

      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      writeFileSync(
        join(homeDir, '.claude', 'settings.json'),
        JSON.stringify({
          outputStyle: 'duet-core',
          additionalDirectories: ['/tmp', '/some/path']
        })
      )

      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)

      expect(agents[0].issues).toBeDefined()
      expect(agents[0].issues).toHaveLength(1)
      expect(agents[0].issues![0].reason_code).toBe('additional_directories')
      expect(agents[0].issues![0].fixable).toBe(true)
      expect(agents[0].status).toBe('needs_setup')
    })

    it('no issue when additionalDirectories is absent', () => {
      writeSessionPrompt(ctx.duetDataDir)

      const stylesDir = join(homeDir, '.claude', 'output-styles')
      const agentsDir = join(homeDir, '.claude', 'agents')
      mkdirSync(stylesDir, { recursive: true })
      mkdirSync(agentsDir, { recursive: true })

      writeFileSync(
        join(stylesDir, 'duet-core.md'),
        expectedOutputStyleFrontmatter() + SESSION_BODY
      )
      writeFileSync(
        join(homeDir, '.claude', 'settings.json'),
        JSON.stringify({ outputStyle: 'duet-core' })
      )
      writeFileSync(
        join(homeDir, '.claude.json'),
        JSON.stringify({ mcpServers: { duet: { type: 'http', url: MCP_URL } } })
      )

      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)

      expect(agents[0].status).toBe('configured')
      expect(agents[0].issues).toBeUndefined()
    })

    it('no issue when additionalDirectories is empty array', () => {
      writeSessionPrompt(ctx.duetDataDir)

      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      writeFileSync(
        join(homeDir, '.claude', 'settings.json'),
        JSON.stringify({ outputStyle: 'duet-core', additionalDirectories: [] })
      )

      const agents = detectAgents(ctx.duetDataDir, TEST_PORT)
      expect(agents[0].issues).toBeUndefined()
    })
  })

  // ===========================================================================
  // fixAgentIssue
  // ===========================================================================

  describe('fixAgentIssue', () => {
    it('removes additionalDirectories from Claude Code settings', () => {
      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      const settingsPath = join(homeDir, '.claude', 'settings.json')
      writeFileSync(
        settingsPath,
        JSON.stringify({
          outputStyle: 'duet-core',
          additionalDirectories: ['/tmp'],
          permissions: { allow: ['Edit'] }
        })
      )

      const result = fixAgentIssue('claude-code', 'additional_directories')

      expect(result).toBe(true)

      const config = JSON.parse(readFileSync(settingsPath, 'utf-8'))
      expect(config.additionalDirectories).toBeUndefined()
      expect(config.outputStyle).toBe('duet-core')
      expect(config.permissions).toEqual({ allow: ['Edit'] })
    })

    it('returns true when additionalDirectories already absent', () => {
      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      writeFileSync(
        join(homeDir, '.claude', 'settings.json'),
        JSON.stringify({ outputStyle: 'duet-core' })
      )

      const result = fixAgentIssue('claude-code', 'additional_directories')
      expect(result).toBe(true)
    })

    it('returns false for unknown agent/reason combination', () => {
      const result = fixAgentIssue('unknown', 'unknown_code')
      expect(result).toBe(false)
    })
  })

  // ===========================================================================
  // configureAllAgents
  // ===========================================================================

  describe('configureAllAgents', () => {
    it('keeps retirement failures visible after successful prompt detection', async () => {
      writeSessionPrompt(ctx.duetDataDir)
      const blocked = join(homeDir, '.claude', 'agents', 'duet-vizir.md')
      mkdirSync(blocked, { recursive: true })
      const results = await configureAllAgents(ctx.duetDataDir, TEST_PORT)
      expect(results[0].status).toBe('needs_setup')
      expect(results[0].details).toContain(blocked)
      expect(results[0].checkedFiles!.every((file) => file.ok)).toBe(true)
    })

    it('does not deploy a stale prompt when the backend build fails', async () => {
      writeSessionPrompt(ctx.duetDataDir, '# Stale prompt')
      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      vi.mocked(fetch).mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          status: 'error',
          output_style: null,
          errors: [
            {
              path: 'duet-core.md',
              reason_code: 'core_prompt_read_error',
              description: 'Missing source'
            }
          ]
        })
      } as Response)
      const results = await configureAllAgents(ctx.duetDataDir, TEST_PORT)
      expect(results[0].status).toBe('needs_setup')
      expect(results[0].details).toContain('Missing source')
      expect(existsSync(join(homeDir, '.claude', 'output-styles'))).toBe(false)
      expect(existsSync(join(homeDir, '.claude', 'settings.json'))).toBe(false)
    })

    it('returns results for all agents', async () => {
      const results = await configureAllAgents(ctx.duetDataDir, TEST_PORT)

      expect(results).toHaveLength(5)
      expect(results[0].id).toBe('claude-code')
      expect(results[1].id).toBe('codex')
      expect(results[2].id).toBe('antigravity')
      expect(results[3].id).toBe('kimi')
      expect(results[4].id).toBe('claude-desktop')
    })

    it('configures all found agents using merged content from disk', async () => {
      writeSessionPrompt(ctx.duetDataDir)

      mkdirSync(join(homeDir, '.claude'), { recursive: true })
      mkdirSync(join(homeDir, '.codex'), { recursive: true })
      mkdirSync(join(homeDir, '.gemini'), { recursive: true })
      mkdirSync(join(homeDir, '.kimi-code'), { recursive: true })
      mkdirSync(claudeDesktopConfigDir(), { recursive: true })
      deployBridge(ctx.duetDataDir)

      const results = await configureAllAgents(ctx.duetDataDir, TEST_PORT)

      expect(results[0].status).toBe('configured')
      expect(results[1].status).toBe('configured')
      expect(results[2].status).toBe('configured')
      expect(results[3].status).toBe('configured')
      expect(results[4].status).toBe('configured')
    })
  })

  // ===========================================================================
  // cleanupLegacyClaudeFiles
  // ===========================================================================

  describe('cleanupLegacyClaudeFiles', () => {
    it('removes generated role files but preserves the new style and personal files', () => {
      const retired = [
        join(homeDir, '.claude', 'output-styles', 'duet-executor.md'),
        join(homeDir, '.claude', 'agents', 'duet-executor.md'),
        join(homeDir, '.claude', 'agents', 'duet-vizir.md'),
        join(ctx.duetDataDir, 'duet-executor.md'),
        join(ctx.duetDataDir, 'duet-vizir.md')
      ]
      for (const path of retired) {
        mkdirSync(join(path, '..'), { recursive: true })
        writeFileSync(path, GENERATED_BODY)
      }
      const personal = join(homeDir, '.claude', 'agents', 'vizir.md')
      writeFileSync(personal, '# Personal instructions')
      configureClaudeCode(SESSION_BODY, ctx.duetDataDir, TEST_PORT)
      for (const path of retired) expect(existsSync(path)).toBe(false)
      expect(readFileSync(personal, 'utf-8')).toBe('# Personal instructions')
      expect(readFileSync(join(homeDir, '.claude', 'output-styles', 'duet-core.md'), 'utf-8')).toBe(
        expectedOutputStyleFrontmatter() + SESSION_BODY
      )
      expect(existsSync(join(homeDir, '.claude', 'agents', 'duet.md'))).toBe(false)
      expect(cleanupLegacyClaudeFiles(ctx.duetDataDir)).toEqual({ removed: [], failed: [] })
    })

    it('preserves unmarked files even when their names match retired roles', () => {
      const path = join(homeDir, '.claude', 'agents', 'duet-vizir.md')
      mkdirSync(join(path, '..'), { recursive: true })
      writeFileSync(path, '# User-owned instructions')
      expect(cleanupLegacyClaudeFiles(ctx.duetDataDir)).toEqual({ removed: [], failed: [] })
      expect(readFileSync(path, 'utf-8')).toBe('# User-owned instructions')
    })

    it('does not retire old files or switch styles without a replacement prompt', () => {
      const path = join(homeDir, '.claude', 'output-styles', 'duet-executor.md')
      mkdirSync(join(path, '..'), { recursive: true })
      writeFileSync(path, GENERATED_BODY)
      const settings = join(homeDir, '.claude', 'settings.json')
      writeFileSync(settings, JSON.stringify({ outputStyle: 'duet-executor' }))
      expect(configureClaudeCode(null, ctx.duetDataDir, TEST_PORT).status).toBe('needs_setup')
      expect(readFileSync(path, 'utf-8')).toBe(GENERATED_BODY)
      expect(JSON.parse(readFileSync(settings, 'utf-8')).outputStyle).toBe('duet-executor')
    })

    it('reports unreadable targets without stopping cleanup', () => {
      const broken = join(homeDir, '.claude', 'agents', 'duet-executor.md')
      mkdirSync(broken, { recursive: true })
      const retired = join(ctx.duetDataDir, 'duet-vizir.md')
      writeFileSync(retired, GENERATED_BODY)
      const result = cleanupLegacyClaudeFiles(ctx.duetDataDir)
      expect(result.removed).toEqual([retired])
      expect(result.failed).toHaveLength(1)
      expect(result.failed[0].path).toBe(broken)
    })
  })
})
