"""Build the platform session prompt from the bundled duet-core.md source."""

from pathlib import Path
import re

from fileio import atomic_write, atomic_write_json


GENERATED_BANNER = (
    "<!-- AUTO-GENERATED by Duet from "
    "@Duet.git/packages/instructions/duet-core.md "
    "— edit the source, not this file -->\n\n"
)


_VERSION_SUFFIX_RE = re.compile(r"_v\d+$")
_SCAN_IGNORE_DIRS = {"old", ".git", "node_modules", "__pycache__"}


def _scan_version_suffixes(base_path: Path) -> list[dict]:
    """Report version-suffixed Markdown sources without blocking the build."""
    errors = []
    for source in sorted(base_path.rglob("*.md")):
        if not source.is_file():
            continue
        if _SCAN_IGNORE_DIRS.intersection(source.relative_to(base_path).parts[:-1]):
            continue
        if _VERSION_SUFFIX_RE.search(source.stem):
            relative_path = source.relative_to(base_path).as_posix()
            errors.append({
                "path": relative_path,
                "reason_code": "version_suffix",
                "description": f"Instruction source has a version suffix: {relative_path}",
            })
    return errors


def merge_duet_instructions(
    core_prompt_path: Path,
    output_dir: Path,
    errors_path: Path,
) -> dict:
    """Write the session prompt and the error cache.

    The function and HTTP endpoint retain their names for existing callers.
    No agent registry, role-specific files, or insertion markers are needed.

    Args:
        core_prompt_path: Bundled platform prompt source.
        output_dir: DuetData directory receiving duet.md.
        errors_path: JSON error cache read by Host.

    Returns:
        Build status, output_style path (None on failure), and errors.
    """
    output_path = output_dir / "duet.md"
    errors = []
    try:
        body = core_prompt_path.read_text(encoding="utf-8")
    except OSError as exc:
        errors.append({
            "path": str(core_prompt_path),
            "reason_code": "core_prompt_read_error",
            "description": f"Cannot read the duet-core platform prompt: {exc}",
        })
    else:
        try:
            output_dir.mkdir(parents=True, exist_ok=True)
            atomic_write(output_path, GENERATED_BANNER + body.rstrip() + "\n")
        except OSError as exc:
            errors.append({
                "path": str(output_path),
                "reason_code": "prompt_write_error",
                "description": f"Cannot write the platform session prompt: {exc}",
            })

    failed = bool(errors)
    if not failed:
        errors.extend(_scan_version_suffixes(core_prompt_path.parent))
    atomic_write_json(errors_path, errors)
    return {
        "status": "error" if failed else "ok",
        "output_style": None if failed else str(output_path),
        "errors": errors,
    }
