#!/usr/bin/env python3
"""
ЧТО: Скрипт генерации карты репозитория (docs/WORKSPACE_MAP.md).
ЗАЧЕМ: Автоматизирует обновление структуры, чтобы люди и агенты видели актуальное состояние проекта.
КТО_ИСПОЛЬЗУЕТ: Keeper, Все агенты, Разработчики.
"""

import json
import os
from pathlib import Path
from typing import Dict, List, Optional, Set
from datetime import datetime

# Configuration Constants
ROOT_DIR = Path(__file__).parent.parent.absolute()
WORKSPACE_MAP_CONFIG_PATH = ROOT_DIR / ".ai" / "workspace_map.json"
DEFAULT_OUTPUT_PATH = ROOT_DIR / "docs" / "WORKSPACE_MAP.md"

def load_json(path: Path) -> Dict:
    if not path.exists():
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"⚠️ Error loading JSON {path}: {e}")
        return {}

class WorkspaceMapper:
    def __init__(self):
        self.config = load_json(WORKSPACE_MAP_CONFIG_PATH)
        self.target_file = ROOT_DIR / self.config.get("target_file", "docs/WORKSPACE_MAP.md")
        self.ignore_patterns = set(self.config.get("ignore_patterns", []))
        self.section_folders_list = self.config.get("section_folders", ["."])
        
        # Derived state
        self.section_folders_set = set(self.section_folders_list)
        self.markdown_lines = []

    def is_ignored(self, path: Path) -> bool:
        """Check if path matches ignore patterns."""
        rel_path = path.relative_to(ROOT_DIR).as_posix()
        name = path.name
        
        for pattern in self.ignore_patterns:
            # Folder pattern (ends with /)
            if pattern.endswith("/"):
                # Check if this folder OR any parent folder is ignored
                # e.g. path="node_modules/foo", pattern="node_modules/" -> Match
                if f"{rel_path}/".startswith(pattern) or f"{name}/" == pattern:
                    return True
            # File pattern
            else:
                if name == path:
                   return True
        return False

    def get_section_metadata(self, folder_path: Path) -> Dict:
        """Load section.json if exists."""
        return load_json(folder_path / "section.json")

    def get_folder_description(self, folder_path: Path, section_meta: Dict, parent_contents: Dict) -> str:
        """
        Determine folder description based on The Rules:
        1. Section Folder -> section.json['description']
        2. Thin/Ignored Folder -> parent_section.json['contents'][folder_name]
        """
        is_section = (folder_path.relative_to(ROOT_DIR).as_posix() in self.section_folders_set or 
                      folder_path.relative_to(ROOT_DIR).as_posix() == ".")
        
        # Case 1: Section Folder
        if is_section:
            desc = section_meta.get("description")
            if desc:
                return desc
            
        # Case 2: Defined in parent contents (Thin/Ignored)
        folder_name = folder_path.name
        if folder_name in parent_contents:
            return parent_contents[folder_name]
            
        return "" # No description found

    def load_existing_header(self) -> str:
        """Preserve manual documentation before the first separator."""
        default_header = "# Структура репозитория\n\n> Auto-generated by `scripts/ai_doc_updater.py`. Do not edit manually."
        
        if not self.target_file.exists():
            return default_header
        
        try:
            content = self.target_file.read_text(encoding="utf-8")
            if "\n---" in content:
                # Use rstrip to prevent accumulating newlines
                return content.split("\n---")[0].rstrip()
            return content.rstrip()
        except Exception:
            return default_header

    def generate_tree(self):
        header = self.load_existing_header()
        self.markdown_lines = [header]
        # Ensure exactly one blank line before the first section separator
        if header:
            self.markdown_lines.append("")
        
        # Iterate strictly through the ordered list of Section Folders defined in Master Plan
        for section_path_str in self.section_folders_list:
            full_path = ROOT_DIR / section_path_str
            if not full_path.exists():
                continue
                
            self.process_section(full_path)

    def process_section(self, folder_path: Path):
        rel_path = folder_path.relative_to(ROOT_DIR).as_posix()
        is_root = rel_path == "."
        
        section_meta = self.get_section_metadata(folder_path)
        
        # Determine Title parts
        path_str = "Duet/" if is_root else f"`{rel_path}/`"
        human_title = section_meta.get("title", "Untitled")

        # Add Separator and Header
        self.markdown_lines.append("---")
        self.markdown_lines.append("")
        
        # Header Level
        level = "##" if len(Path(rel_path).parts) <= 1 else "###"
        
        self.markdown_lines.append(f"{level} {path_str} — {human_title}")
        self.markdown_lines.append("")
        
        desc = section_meta.get("description", "")
        if desc:
            self.markdown_lines.append(f"{desc}")
            self.markdown_lines.append("")
        
        self.markdown_lines.append("```")
        # Root folder name visualization
        root_name = folder_path.name + "/" if not is_root else "Duet/"
        self.markdown_lines.append(root_name)
        
        # Capture all raw entries flattened (DFS order)
        raw_entries = []
        self.list_folder_contents_tree(folder_path, section_meta.get("folders", {}), prefix="", accumulator=raw_entries)
        
        # Render aligned
        self.render_aligned_block(raw_entries)
        
        self.markdown_lines.append("```")
        self.markdown_lines.append("")

    def render_aligned_block(self, entries: List[Dict]):
        """Render entries with group-aware alignment"""
        if not entries: return

        # 1. Split into groups separated by spacers
        groups = []
        current_group = []
        
        for entry in entries:
            if entry.get("is_spacer"):
                if current_group:
                    groups.append({"type": "group", "items": current_group})
                    current_group = []
                groups.append({"type": "spacer", "item": entry})
            else:
                current_group.append(entry)
        
        if current_group:
            groups.append({"type": "group", "items": current_group})

        # 2. Process and Render
        running_max_len = 0
        
        for group in groups:
            if group["type"] == "spacer":
                self.markdown_lines.append(group["item"]["tree"])
                continue
            
            items = group["items"]
            
            # Calculate alignment width for this group
            # Rule: Binary files do NOT contribute to width expansion
            group_max_len = 0
            for entry in items:
                if not entry.get("is_binary", False):
                    group_max_len = max(group_max_len, len(entry["tree"]))
            
            # Fallback: if all are binary or group is empty?
            # Only force expansion if we don't have a running max yet
            if group_max_len == 0 and items and running_max_len == 0:
                 group_max_len = max(len(entry["tree"]) for entry in items)

            # Monotonic alignment: Never decrease width
            running_max_len = max(running_max_len, group_max_len)

            target_col = running_max_len + 4
            
            for entry in items:
                tree_part = entry["tree"]
                comment = entry["comment"]
                
                comment_str = ""
                if comment:
                    # If this item didn't contribute to width (binary) but has a comment,
                    # we still try to align it IF it fits. If it sticks out, we space it by 1.
                    
                    # Wait, simplified: Just pad to target_col.
                    if len(tree_part) < target_col:
                        padding = " " * (target_col - len(tree_part))
                        comment_str = f"{padding}# {comment}"
                    else:
                        # It sticks out (e.g. long binary name). Just add 1 space.
                        comment_str = f" # {comment}"
                
                self.markdown_lines.append(f"{tree_part}{comment_str}")

    def list_folder_contents_tree(self, folder_path: Path, context_map: Dict, prefix: str, accumulator: List[Dict], section_root: Optional[Path] = None):
        if section_root is None: section_root = folder_path

        try:
            items = list(folder_path.iterdir())
        except PermissionError:
            return

        # 1. Classify and Filter
        files = []
        folders = []
        
        binary_extensions = ['.ico', '.png', '.svg', '.zip', '.exe', '.dmg', '.pdf', '.jpg', '.jpeg', '.gif', '.mp4', '.mov', '.webp', '.ttf', '.otf', '.woff', '.woff2', '.eot']

        for item in items:
            name = item.name
            
            # Use ignore patterns from config for filtering
            # We no longer hardcode dotfile exclusions here.
            
            # Ignore Logic
            is_dir = item.is_dir()
            
            # File Ignore
            if not is_dir:
                is_ignored = False
                for p in self.ignore_patterns:
                    if not p.endswith("/") and name == p:
                        is_ignored = True
                        break
                if is_ignored: continue
                files.append(item)
            
            # Folder Ignore (Keep but tag)
            else:
                folders.append(item)
        
        # Refine Files: Filter out companion files (e.g. package.json.md if package.json exists)
        all_item_names = {item.name for item in items}
        files = [f for f in files if not (f.name.endswith(".md") and f.name[:-3] in all_item_names)]

        # 2. Sort (Alphabetical)
        files.sort(key=lambda x: x.name.lower())
        folders.sort(key=lambda x: x.name.lower())
        
        # 3. Build Sequence with Spacers
        sequence = []
        
        # Files first
        sequence.extend([{"type": "file", "item": f} for f in files])
        
        # Spacer between files and folders
        if files and folders:
             sequence.append({"type": "spacer", "item": None})
             
        # Folders interleaved with spacers
        for i, folder in enumerate(folders):
             sequence.append({"type": "folder", "item": folder})
             if i < len(folders) - 1:
                 sequence.append({"type": "spacer", "item": None})
        
        # 4. Generate Entries
        count = len(sequence)
        
        for i, entry in enumerate(sequence):
            is_last = (i == count - 1)
            entry_type = entry["type"]
            item = entry["item"]
            
            # Connectors
            connector = "└── " if is_last else "├── "
            child_prefix = "    " if is_last else "│   "
            
            if entry_type == "spacer":
                tree_part = f"{prefix}│"
                accumulator.append({
                    "tree": tree_part,
                    "comment": "",
                    "is_spacer": True
                })
                continue
            
            # Processing File/Folder
            name = item.name
            is_dir = item.is_dir()
            
            rel_from_root = item.relative_to(ROOT_DIR).as_posix()
            
            # Section Check
            is_section = False
            if is_dir and rel_from_root in self.section_folders_set:
                is_section = True
            
            # Folder Ignore Check
            is_folder_ignored = False
            if is_dir:
                for p in self.ignore_patterns:
                    if p.endswith("/") and (name + "/") == p: 
                        is_folder_ignored = True
                        break
            
            is_binary = False
            if not is_dir:
                is_binary = item.suffix.lower() in binary_extensions

            # Display Name Suffix
            display_name = name
            if is_dir and (is_section or is_folder_ignored):
                display_name = f"{name}/**"
            
            suffix = "/" if is_dir else ""
            tree_part = f"{prefix}{connector}{display_name}{suffix}"
            
            # Description
            description = ""
            if is_section:
                rel_key = item.relative_to(section_root).as_posix()
                ctx_desc = context_map.get(rel_key, "")
                description = f"[РАЗДЕЛ] {ctx_desc}" if ctx_desc else "[РАЗДЕЛ]"
            else:
                rel_key = item.relative_to(section_root).as_posix()
                description = context_map.get(rel_key, "")
            
            is_self_documenting = name in ["LICENSE", "README.md"]
            if is_self_documenting: description = ""
            
            if not description and not is_dir and not is_self_documenting and not is_binary:
                description = self.get_file_header_description(item)
            
            # Comment Formatting
            comment_parts = []
            if is_folder_ignored:
                comment_parts.append("(git ignored)")
            
            if description:
                comment_parts.append(description)
            elif (not is_dir) or (is_dir and not is_section and not is_folder_ignored):
                 # Missing docs logic
                 if not is_self_documenting and not is_binary:
                     comment_parts.append("[MISSING DOCS!]")

            comment = " ".join(comment_parts)
            
            # Add to accumulator
            accumulator.append({
                "tree": tree_part,
                "comment": comment,
                "item": item,
                "is_binary": is_binary,
                "is_spacer": False
            })
            
            # Recurse
            if is_dir and not is_folder_ignored and not is_section:
                self.list_folder_contents_tree(item, context_map, prefix + child_prefix, accumulator, section_root)

    # Overload/Fix the recursive call to match signature
    def get_file_header_description(self, file_path: Path) -> str:
        """Attempt to extract description from file content."""
        if not file_path.exists() or file_path.is_dir():
            return ""
            
        try:
            # 1. JSON: Check _DOC only
            if file_path.suffix == ".json":
                try:
                    with open(file_path, "r", encoding="utf-8") as f:
                        data = json.load(f)
                        if "_DOC" in data and isinstance(data["_DOC"], dict):
                            # Prioritize ЧТО as requested (Strict spec compliance)
                            return data["_DOC"].get("ЧТО", "")
                except:
                    pass
            
            # 2. Markdown: Check first header
            if file_path.suffix == ".md":
                try:
                    with open(file_path, "r", encoding="utf-8") as f:
                        for line in f:
                            if line.strip().startswith("# "):
                                return line.strip().replace("# ", "").strip()
                            if line.strip() and not line.startswith("#"):
                                # If first non-empty line isn't header, maybe it's title? 
                                # Let's be strict: Markdown needs a title.
                                break 
                except:
                    pass

            # 3. Code (TS, JS, PY, etc): Check "ЧТО:" or "Description:" or "Purpose:"
            # Read first 2KB is usually enough
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                content_head = f.read(2048)
                
            import re
            # Match "ЧТО: <text>" or "Description: <text>"
            # Support // or # or /* style comments
            # Regex: Look for pattern after comment start, until newline
            match = re.search(r"(?:ЧТО|Description|Цель|Purpose)\s*:\s*(.+)", content_head, re.IGNORECASE)
            if match:
                return match.group(1).strip()
            
            # 4. Companion File Check (e.g. package.json -> package.json.md)
            # Check if there is a file with .md appended
            companion_path = file_path.with_name(file_path.name + ".md")
            if companion_path.exists():
                with open(companion_path, "r", encoding="utf-8", errors="ignore") as f:
                    content_head = f.read(2048)
                
                # Use same regex to find "ЧТО:" in companion file
                match = re.search(r"(?:ЧТО|Description|Цель|Purpose)\s*:\s*(.+)", content_head, re.IGNORECASE)
                if match:
                    return match.group(1).strip()
                
        except Exception:
            pass
            
        return ""

    def save(self):
        self.target_file.parent.mkdir(parents=True, exist_ok=True)
        with open(self.target_file, "w", encoding="utf-8") as f:
            f.write("\n".join(self.markdown_lines))
        print(f"✅ Map updated: {self.target_file}")

if __name__ == "__main__":
    mapper = WorkspaceMapper()
    mapper.generate_tree()
    mapper.save()
